# Configuração global do site
title: "Minhas Novels e Mangas"
description: "Plataforma para múltiplas novels de aventura, ação, drama e fantasia"
baseurl: "/minhas-novels"      # deixe vazio se o site estiver em https://SEU-USUARIO.github.io/
url: "https://tdaniloj.github.io"  # substitua pelo seu usuário do GitHub

# Tema (não usado, mas necessário para GitHub Pages)
theme: minima

# Parser Markdown
markdown: kramdown
kramdown:
  input: GFM

# Configurações personalizadas
collections:
  novels:
    output: true
    permalink: /:collection/:name/