# Configurações básicas do site
title: "Minha Biblioteca de Novels"
description: "Plataforma para múltiplas novels de aventura, ação, drama e fantasia"
baseurl: ""      # Deixe vazio se o site for no root do GitHub Pages
url: "https://https://tdaniloj.github.io"  # Substitua pelo seu usuário

# Tema (não usamos nenhum tema pronto, CSS customizado)
theme: minima      # Pode deixar assim, ou retirar se não quiser usar tema

# Plugins (opcional)
plugins: []

# Opções de Markdown
markdown: kramdown
kramdown:
  input: GFM
